/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package nikeshoeshop;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import com.mongodb.MongoClient;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vivek
 */
public class add1 extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public add1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        userid = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        cart = new javax.swing.JButton();
        AboutUs = new javax.swing.JButton();
        popular = new javax.swing.JButton();
        home = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        fail = new javax.swing.JLabel();
        go1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("User ID :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, -1, -1));

        jLabel5.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, -1, 10));

        userid.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        getContentPane().add(userid, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 370, 360, -1));

        login.setBackground(new java.awt.Color(0, 0, 0));
        login.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 550, 120, 40));

        jLabel6.setFont(new java.awt.Font("Andalus", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ADMINISTRATOR LOGIN");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setText("*admin only");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 690, -1, -1));

        add.setBackground(new java.awt.Color(0, 0, 0));
        add.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("Add new shoes to database");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 660, 190, 30));

        cart.setBackground(new java.awt.Color(0, 0, 0));
        cart.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        cart.setForeground(new java.awt.Color(255, 255, 255));
        cart.setText("view cart");
        cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartActionPerformed(evt);
            }
        });
        getContentPane().add(cart, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 70, -1, -1));

        AboutUs.setBackground(new java.awt.Color(0, 0, 0));
        AboutUs.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        AboutUs.setForeground(new java.awt.Color(255, 255, 255));
        AboutUs.setText("About Us");
        AboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsActionPerformed(evt);
            }
        });
        getContentPane().add(AboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 70, -1, -1));

        popular.setBackground(new java.awt.Color(0, 0, 0));
        popular.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        popular.setForeground(new java.awt.Color(255, 255, 255));
        popular.setText("popular products");
        popular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popularActionPerformed(evt);
            }
        });
        getContentPane().add(popular, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        home.setBackground(new java.awt.Color(0, 0, 0));
        home.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        password.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 420, 360, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nikepics/pix/admin.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 400, 280));

        fail.setFont(new java.awt.Font("Andalus", 0, 36)); // NOI18N
        fail.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(fail, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, 420, 40));

        go1.setBackground(new java.awt.Color(0, 0, 0));
        go1.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        go1.setForeground(new java.awt.Color(255, 255, 255));
        go1.setText("SEARCH");
        go1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                go1ActionPerformed(evt);
            }
        });
        getContentPane().add(go1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 250, 30));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setOpaque(false);
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 270, 50));

        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nikepics/home/Nike Wallpaper 4.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        add1 a=new add1();
        this.dispose();
        a.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void cartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartActionPerformed
        cart a=new cart();
        a.pop();
        this.dispose();
        a.setVisible(true);
    }//GEN-LAST:event_cartActionPerformed

    private void AboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsActionPerformed
        AboutUs a=new AboutUs();
        this.dispose();
        a.setVisible(true);
    }//GEN-LAST:event_AboutUsActionPerformed

    private void popularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popularActionPerformed
        popular a=new popular();
        this.dispose();
        a.setVisible(true);
    }//GEN-LAST:event_popularActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        home a= new home();
        this.dispose();
        a.setVisible(true);
    }//GEN-LAST:event_homeActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        //Add2 a=new Add2();
        //this.dispose();
       // a.setVisible(true);
        
        
        
        try{   
         MongoClient mongoClient = new MongoClient( "localhost" , 27017 );          //to connect to mongodb server
         DB db = mongoClient.getDB( "nikeshop" );                                      //connect to database
         System.out.println("Connected to database successfully");
         DBCollection coll=db.getCollection("admin");                                   //using a collection via object prod      
         
         String id=userid.getText();
         String pass=password.getText();
         BasicDBObject query=new BasicDBObject("uid",id);
         DBCursor pointer = coll.find(query);
         
          
        //BasicDBObject query=new BasicDBObject("sub_category","men");   
        //DBCursor pointer=prod.find(query);
         
         
            if(pointer.hasNext())
            {   System.out.println("admin record found");
                DBObject pr=pointer.next();
                String pas=(String) pr.get("password");
                
                if(pas.equals(pass))
                {   Add2 a=new Add2();
                    this.dispose();
                     a.setVisible(true);
                }
                else
                {   System.out.println("admin record NOT found");
                    fail.setText("INCORRECT PASSWORD");
                }
            }
                  
            
            else
            fail.setText("INCORRECT USER ID");
         
         
         }
	catch(Exception e)
         {
	     System.err.println( e.getClass().getName() + ": " + e.getMessage() );
             fail.setText("LOGIN FAILED");
	 }
        
        
        
        
      
        
    }//GEN-LAST:event_loginActionPerformed

    private void go1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_go1ActionPerformed
        searchResult a=new searchResult();
        this.dispose();
        a.setVisible(true);
    }//GEN-LAST:event_go1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutUs;
    private javax.swing.JButton add;
    private javax.swing.JLabel background;
    private javax.swing.JButton cart;
    private javax.swing.JLabel fail;
    private javax.swing.JButton go1;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton popular;
    private javax.swing.JTextField userid;
    // End of variables declaration//GEN-END:variables
}
