/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package nikeshoeshop;

import javax.swing.table.DefaultTableModel;
import static nikeshoeshop.NikeShoeShop.*;

/**
 *
 * @author vivek
 */
public class bill extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public bill() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        las = new javax.swing.JButton();
        generate = new javax.swing.JButton();
        m = new javax.swing.JLabel();
        m1 = new javax.swing.JLabel();
        m4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        billtable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        billtable2 = new javax.swing.JTable();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        las.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        las.setText("PROCEED");
        las.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lasActionPerformed(evt);
            }
        });
        getContentPane().add(las, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 670, -1, -1));

        generate.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        generate.setText("generate bill");
        generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateActionPerformed(evt);
            }
        });
        getContentPane().add(generate, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, -1));

        m.setFont(new java.awt.Font("Andalus", 0, 24)); // NOI18N
        m.setText("Address : ");
        getContentPane().add(m, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 1240, -1));

        m1.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        m1.setText("CUSTOMER  DETAILS: ");
        getContentPane().add(m1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        m4.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        m4.setText("PRODUCT  DETAILS : ");
        getContentPane().add(m4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, -1, -1));

        billtable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        billtable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "EMAIL", "PHONE NO.", "TOTAL AMOUNT", "PAYMENT METHOD"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(billtable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 1210, 100));

        billtable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "p_id", "category", "sub category", "product name", "size", "MRP", "discount", "price", "quantity left"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(billtable2);
        if (billtable2.getColumnModel().getColumnCount() > 0) {
            billtable2.getColumnModel().getColumn(3).setPreferredWidth(225);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 1210, 230));

        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nikepics/home/nike-hd-20 -2.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
     public void gen()
     {generate.doClick();}
    private void generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateActionPerformed
            int i=0;String paym;
            DefaultTableModel tm1=(DefaultTableModel)billtable1.getModel();
            tm1.setRowCount(0);
            if(COD==1)
            paym="CASH ON DELIVERY";
            else if(COD==-1)
            paym="ONLINE BANKING";
            else
            paym="NOT SPECIFIED";
            tm1.addRow(new Object[]{Sname,Semail,Sphoneno,AMOUNT_to_pay,paym});
            
            m.setText("Address : "+Saddress);
            
            DefaultTableModel tm2=(DefaultTableModel)billtable2.getModel();
            tm2.setRowCount(0);
            for(i=0;i<=Ccount;i++)
                    {tm2.addRow(new Object[]{Cid[i],Ccat.get(i),Cscat.get(i),Cpname.get(i),Csize[i],Cmrp[i],Cdiscount[i],Cprice[i],Cqtyleft[i]});}
    }//GEN-LAST:event_generateActionPerformed

    private void lasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lasActionPerformed
        last a=new last();
        this.dispose();
        a.setVisible(true);
    }//GEN-LAST:event_lasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JTable billtable1;
    public javax.swing.JTable billtable2;
    private javax.swing.JButton generate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton las;
    private javax.swing.JLabel m;
    private javax.swing.JLabel m1;
    private javax.swing.JLabel m4;
    // End of variables declaration//GEN-END:variables
}
