/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package nikeshoeshop;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import static nikeshoeshop.NikeShoeShop.*;

/**
 *
 * @author vivek
 */
public class OnlineBanking1 extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public OnlineBanking1() {
        initComponents();
    }
    
    public static boolean isNumeric(String str)  
    {  
                        try  
                                    {  
                                     double d = Double.parseDouble(str);  
                                      }  
                        catch(NumberFormatException nfe)  
                                     {  
                                         return false;  
                                     }  
                         return true;  
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sp = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        phoneno = new javax.swing.JTextField();
        previous = new javax.swing.JButton();
        next = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        cart = new javax.swing.JButton();
        AboutUs = new javax.swing.JButton();
        popular = new javax.swing.JButton();
        home = new javax.swing.JButton();
        msg1 = new javax.swing.JLabel();
        msg2 = new javax.swing.JLabel();
        go1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Name :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 540, 30));
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 540, 30));

        jLabel6.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" address :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, -1, -1));

        address.setColumns(20);
        address.setRows(5);
        sp.setViewportView(address);

        getContentPane().add(sp, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 540, 160));

        jLabel7.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("phone number(+91) :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 570, 160, 30));

        phoneno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phonenoKeyTyped(evt);
            }
        });
        getContentPane().add(phoneno, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 570, 540, 30));

        previous.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        previous.setText("PREVIOUS");
        previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousActionPerformed(evt);
            }
        });
        getContentPane().add(previous, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 630, 120, 50));

        next.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        next.setText("NEXT");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 630, 120, 50));

        jLabel8.setFont(new java.awt.Font("Andalus", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Please enter your details :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setText("*admin only");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 690, -1, -1));

        add.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        add.setText("Add new shoes to database");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 660, 190, 30));

        cart.setBackground(new java.awt.Color(0, 0, 0));
        cart.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        cart.setForeground(new java.awt.Color(255, 255, 255));
        cart.setText("view cart");
        cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartActionPerformed(evt);
            }
        });
        getContentPane().add(cart, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 70, -1, -1));

        AboutUs.setBackground(new java.awt.Color(0, 0, 0));
        AboutUs.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        AboutUs.setForeground(new java.awt.Color(255, 255, 255));
        AboutUs.setText("About Us");
        AboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsActionPerformed(evt);
            }
        });
        getContentPane().add(AboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 70, -1, -1));

        popular.setBackground(new java.awt.Color(0, 0, 0));
        popular.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        popular.setForeground(new java.awt.Color(255, 255, 255));
        popular.setText("popular products");
        popular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popularActionPerformed(evt);
            }
        });
        getContentPane().add(popular, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        home.setBackground(new java.awt.Color(0, 0, 0));
        home.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        msg1.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        msg1.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(msg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 280, 290, 30));

        msg2.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        msg2.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(msg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 570, 290, 30));

        go1.setBackground(new java.awt.Color(0, 0, 0));
        go1.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        go1.setForeground(new java.awt.Color(255, 255, 255));
        go1.setText("SEARCH");
        go1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                go1ActionPerformed(evt);
            }
        });
        getContentPane().add(go1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 250, 30));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setOpaque(false);
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 270, 50));

        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nikepics/home/Nike Wallpaper 6.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        add1 a=new add1();
        this.dispose();
        a.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void cartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartActionPerformed
        cart a=new cart();
        a.pop();
        this.dispose();
        a.setVisible(true);
    }//GEN-LAST:event_cartActionPerformed

    private void AboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsActionPerformed
        AboutUs a=new AboutUs();
        this.dispose();
        a.setVisible(true);
    }//GEN-LAST:event_AboutUsActionPerformed

    private void popularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popularActionPerformed
        popular a=new popular();
        this.dispose();
        a.setVisible(true);
    }//GEN-LAST:event_popularActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        home a= new home();
        this.dispose();
        a.setVisible(true);
    }//GEN-LAST:event_homeActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
    msg1.setText(null);
    msg2.setText(null);
        
        Sname=name.getText();
        Sphoneno=phoneno.getText();
                if(!(isNumeric(Sphoneno)))
                {   msg2.setText("Invalid phone number");
                }
        
        Semail=email.getText();
        String EMAIL_REJECT = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
                if(!Semail.matches(EMAIL_REJECT)||Semail.equals(""))
                {  msg1.setText("Invalid E-mail ID");
                }
                
        Saddress=address.getText();
        
        if((msg1.getText()==null)&&(msg2.getText()==null))
        {   OnlineBanking2 a=new OnlineBanking2();
            this.dispose();        
            a.setVisible(true); 
        }
    }//GEN-LAST:event_nextActionPerformed

    private void previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousActionPerformed
        payoption a=new payoption();
        this.dispose();
        a.setVisible(true);
    }//GEN-LAST:event_previousActionPerformed

    private void phonenoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phonenoKeyTyped
        
    }//GEN-LAST:event_phonenoKeyTyped

    private void go1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_go1ActionPerformed
        searchResult a=new searchResult();
        this.dispose();
        a.setVisible(true);
    }//GEN-LAST:event_go1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OnlineBanking1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OnlineBanking1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OnlineBanking1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OnlineBanking1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OnlineBanking1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutUs;
    private javax.swing.JButton add;
    private javax.swing.JTextArea address;
    private javax.swing.JLabel background;
    private javax.swing.JButton cart;
    private javax.swing.JTextField email;
    private javax.swing.JButton go1;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel msg1;
    private javax.swing.JLabel msg2;
    private javax.swing.JTextField name;
    private javax.swing.JButton next;
    private javax.swing.JTextField phoneno;
    private javax.swing.JButton popular;
    private javax.swing.JButton previous;
    private javax.swing.JScrollPane sp;
    // End of variables declaration//GEN-END:variables
}
