/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package nikeshoeshop;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import com.mongodb.MongoClient;
import com.mongodb.WriteConcern;
import javax.swing.JOptionPane;
import static nikeshoeshop.NikeShoeShop.*;

/**
 *
 * @author vivek
 */
public class OnlineBanking3pass extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public OnlineBanking3pass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transactionbutton = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        m1 = new javax.swing.JLabel();
        m3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        cart = new javax.swing.JButton();
        AboutUs = new javax.swing.JButton();
        popular = new javax.swing.JButton();
        home = new javax.swing.JButton();
        m2 = new javax.swing.JLabel();
        m4 = new javax.swing.JLabel();
        go1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        transactionbutton.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        transactionbutton.setText("COMPLETE TRANSACTION");
        transactionbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(transactionbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 640, 190, 30));

        refresh.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        refresh.setText("REFRESH");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        getContentPane().add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 640, 190, 30));

        jLabel6.setFont(new java.awt.Font("Andalus", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Login successful");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        m1.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        m1.setForeground(new java.awt.Color(255, 255, 255));
        m1.setText("welcome mr.");
        getContentPane().add(m1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        m3.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        m3.setForeground(new java.awt.Color(255, 255, 255));
        m3.setText("Amount to pay:");
        getContentPane().add(m3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("*admin only");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 690, -1, -1));

        add.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        add.setText("Add new shoes to database");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 660, 190, 30));

        cart.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        cart.setText("view cart");
        cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartActionPerformed(evt);
            }
        });
        getContentPane().add(cart, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 70, -1, -1));

        AboutUs.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        AboutUs.setText("About Us");
        AboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsActionPerformed(evt);
            }
        });
        getContentPane().add(AboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 70, -1, -1));

        popular.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        popular.setText("popular products");
        popular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popularActionPerformed(evt);
            }
        });
        getContentPane().add(popular, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        home.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        m2.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        m2.setForeground(new java.awt.Color(255, 255, 255));
        m2.setText("Account Balance: ");
        getContentPane().add(m2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, -1, -1));

        m4.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        m4.setForeground(new java.awt.Color(255, 255, 255));
        m4.setText("Balance After Transaction:");
        getContentPane().add(m4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, -1, -1));

        go1.setBackground(new java.awt.Color(0, 0, 0));
        go1.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        go1.setForeground(new java.awt.Color(255, 255, 255));
        go1.setText("SEARCH");
        go1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                go1ActionPerformed(evt);
            }
        });
        getContentPane().add(go1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 250, 30));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setOpaque(false);
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 270, 50));

        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nikepics/home/Nike Wallpaper 6.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void ref()
        {refresh.doClick();}
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        add1 a=new add1();
        this.dispose();
        a.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void cartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartActionPerformed
        cart a=new cart();
        a.pop();
        this.dispose();
        a.setVisible(true);
    }//GEN-LAST:event_cartActionPerformed

    private void AboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsActionPerformed
        AboutUs a=new AboutUs();
        this.dispose();
        a.setVisible(true);
    }//GEN-LAST:event_AboutUsActionPerformed

    private void popularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popularActionPerformed
        popular a=new popular();
        this.dispose();
        a.setVisible(true);
    }//GEN-LAST:event_popularActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        home a= new home();
        this.dispose();
        a.setVisible(true);
    }//GEN-LAST:event_homeActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        m1.setText("welcome mr. "+CUST_name);
        m2.setText("Account Balance: "+ACC_balance);
        m3.setText("Amount to pay: "+AMOUNT_to_pay);
        double bal_left=ACC_balance-AMOUNT_to_pay;
        m4.setText("Balance After Transaction: "+bal_left);
    }//GEN-LAST:event_refreshActionPerformed

    private void transactionbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionbuttonActionPerformed
        double left=0;
        

try{
         MongoClient mongoClient = new MongoClient( "localhost" , 27017 );
         mongoClient.setWriteConcern(WriteConcern.JOURNALED);
         DB db = mongoClient.getDB( "nikeshop" );
	 System.out.println("Connect to database successfully");
         DBCollection coll = db.getCollection("customer");
         //DBCollection prod = db.getCollection("Product");		

        //i=  Integer.parseInt(jTextField1.getText());
        
        //j=jPasswordField1.getText();
  
                    BasicDBObject query = new BasicDBObject("acc_no",ACC_no);
                    DBCursor cursor = coll.find(query);
                        
                    
                            DBObject obj= cursor.next();
                            left=ACC_balance-AMOUNT_to_pay;
                            obj.put("balance",left);
                            coll.save(obj);
                            JOptionPane.showMessageDialog(null, "Transaction Complete");
                            bill a=new bill();
                            a.gen();
                            this.dispose();
                            a.setVisible(true);
                           
                    
    }

                                               
catch(Exception e){
	     System.err.println( e.getClass().getName() + ": " + e.getMessage() );
             
                    }        
    }//GEN-LAST:event_transactionbuttonActionPerformed

    private void go1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_go1ActionPerformed
        searchResult a=new searchResult();
        this.dispose();
        a.setVisible(true);
    }//GEN-LAST:event_go1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OnlineBanking3pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OnlineBanking3pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OnlineBanking3pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OnlineBanking3pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OnlineBanking3pass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutUs;
    private javax.swing.JButton add;
    private javax.swing.JLabel background;
    private javax.swing.JButton cart;
    private javax.swing.JButton go1;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel m1;
    private javax.swing.JLabel m2;
    private javax.swing.JLabel m3;
    private javax.swing.JLabel m4;
    private javax.swing.JButton popular;
    private javax.swing.JButton refresh;
    private javax.swing.JButton transactionbutton;
    // End of variables declaration//GEN-END:variables
}
